name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"
    
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: json
        ini-values: date.timezone=Europe/Paris
    - name: Check PHP Version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script tests

  with_prime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prime-version: ['1.2.0', '1.3.0', '2.0.0']
    name: With prime version ${{ matrix.prime-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Paris"

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: json
          ini-values: date.timezone=Europe/Paris
      - name: Check PHP Version
        run: php -v

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install prime adapter
        run: composer require -W --dev 'b2pweb/bdf-prime:~${{ matrix.prime-version }}@dev'

      - name: Run test suite
        run: composer run-script tests

#
#  analysis:
#    name: Analysis
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Set Timezone
#      uses: szenius/set-timezone@v1.0
#      with:
#        timezoneLinux: "Europe/Paris"
#
#    - name: Install PHP
#      uses: shivammathur/setup-php@v2
#      with:
#        php-version: 7.4
#        extensions: json
#        ini-values: date.timezone=Europe/Paris
#
#    - name: Install Infection
#      run: composer global require infection/infection
#
#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict
#
#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress
#
#    - name: Run type coverage
#      run: composer run-script psalm
#
#    - name: Run Infection
#      run: |
#        git fetch --depth=1 origin $GITHUB_BASE_REF
#        ~/.composer/vendor/bin/infection --logger-github --git-diff-filter=AM
